name: github-actions-demo
run-name: ${{ github.actor }} test KnightSoul
on: [push]
jobs:
  runs-github-actions-demo-with-adopt-hotspot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot' # See 'Supported distributions' for available options
          java-version: '11'
      - run: |
          ./gradlew tests:test
